markdown: kramdown
exclude:
  - LICENSE
  - Makefile
  - README
markdown_ext: "md"

layouts_dir: ./_noita
baseurl: /psyc20100
learn_obj: https://duke.coursera.org/duke-statistics-001/wiki
openintro: https://www.openintro.org/os
teams: 

gems:
  - jemoji

noita:
  name: PSYC 20100 - Psychological Statistics (Autumn 2016)
  description: PSYC 20100 at U Chicago - taught by Daniel Yurovsky
  author:
    name: Dan Yurovsky
    url: http://home.uchicago.edu/~yurovsky
    absolute: true
  lang: en
  topbar:
    toggle: Menu
    right:
      - name: Schedule
        url: /
      - name: Info
        url: /info/
      - name: Syllabus
        url: /syllabus/
      - name: Links
        url: /links/
      - name: FAQ
        url: /faq/
